### ISSUE TITLE
app.render_template: OSError: [Errno 2] ENOENT (esp8266)

### ISSUE THREAD

**Issue by DrakoPOD** [pfalcon/picoweb#74]
Following the example for a temple, I get an error:

```
INFO:picoweb:670016527.176 <HTTPRequest object at 3fff1fe0> <Stream object at 3fff1e10> "GET /template"
ERROR:picoweb:670016527.176 <HTTPRequest object at 3fff1fe0> <Stream object at 3fff1e10> OSError(2,)
Traceback (most recent call last):
  File "picoweb/__init__.py", line 206, in _handle
  File "<stdin>", line 32, in templt
  File "picoweb/__init__.py", line 263, in render_template
  File "picoweb/__init__.py", line 260, in _load_template
  File "utemplate/source.py", line 182, in load
  File "utemplate/source.py", line 169, in input_open
OSError: [Errno 2] ENOENT
```
I have picoweb and utemplate in modules (frozen).

I readed that this error occurs when the server can't find the file.

**Comment by Kocin-sb** [comment]
Hi,
Were you able to resolve this issue?
